name: Run Telegram Bot 24/7

on:
  push:
  branches: [main]]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - name: Set up Python
    uses: action/setup-python@v4
    with:
      python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run bot
      run: python app.py
